### ISSUE TITLE
[FIX ] /usr/share/icons/Lila_HD/actions/scalable/go-home.svg -> /home/ilnanny/Scrivania/Lila-HD-icon-theme/Lila_HD/places/scalable/go-home.svg

### ISSUE THREAD

**Issue by Pival81** [ilnanny/Lila-HD-icon-theme#1]
Ciao, spero non ti dia fastidio che parlo in italiano, volevo solo dirti che mi sa che c'è un errore, sicuramente una svista:
mentre facevo un pacchetto rpm sull'opensuse build system, tutto fila liscio finchè non fa certi controlli, ed esce un unico errore:
```
[  123s] ERROR: link target doesn't exist (neither in build root nor in installed system):
[  123s]   /usr/share/icons/Lila_HD/actions/scalable/go-home.svg -> /home/ilnanny/Scrivania/Lila-HD-icon-theme/Lila_HD/places/scalable/go-home.svg
```
Penso che da qualche parte hai lasciato il link alla tua cartella personale, ma non saprei proprio come modificarlo...

**Comment by ilnanny** [comment]
Grazie mille , @Pival81 per la segnalazione.

**Comment by Pival81** [comment]
@ilnanny potresti perfavore avvisarmi con un commento quando hai risolto, così posso far ripartire la compilazione del pacchetto?

**Comment by ilnanny** [comment]
@Pival81 ok adesso è apposto ,ci ho messo un pò perchè ho fixato altre icone e altri 3 simlink corrotti.
Grazie.
ps. Fammi sapere quando e dove carichi gli .rpm che gli aggiungo alla lista . Grazie.
nel caso puoi scrivermi a cristianpozzessere at gmail dot com .
