### ISSUE TITLE
[ FIX ] Themes Lila_HD_* not contain link file

### ISSUE THREAD

**Issue by ivoarch** [ilnanny/Lila-HD-icon-theme#2]
Hi, I have seen that the other Lila_HD_* not contain a [link](https://raw.githubusercontent.com/ilnanny/Lila-HD-icon-theme/master/Lila_HD/link) file ?

**Comment by ilnanny** [comment]
@ivoarch 
This is an old personal note, how and where to create the symbolic links.
It is not valid for any configuration .The I delete immediately.
Thanks for pointing out that.
