### ISSUE TITLE
[ FIX ] Icon Request:  xfce4-pulseaudio-plugin

### ISSUE THREAD

**Issue by ivoarch** [ilnanny/Lila-HD-icon-theme#4]
**Icon Request**

- xfce4-pulseaudio-plugin
- Xfce panel plugin for pulseaudio mixer control

![preview](http://storage7.static.itmages.ru/i/17/0519/h_1495216330_7649038_49fce16b9b.png)

Thanks!

**Comment by ilnanny** [comment]
@ivoarch 
The icon "xfce4-pulseaudio-plugin"is present in multiple folders of the Theme,see in the last update :

Lila_HD/status/scalable/xfce4-pulseaudio-plugin.svg
Lila_HD/apps/scalable/xfce4-pulseaudio-plugin.svg
Lila_HD/notifications/scalable/xfce4-pulseaudio-plugin.svg

But equally ,on the panel of the XFCe ,it is shown the icon for the file .symbolic .
I tried to check also with other icon packs ,but the problem persists.
I don't know if it is a small bug in the panel in xfce, or if there is some setting that I do not know .
I'm sorry ,but for now do not know how to solve the problem.
With Alsa ,the icon is displayed correct ,even with pnmixer.

**Comment by ivoarch** [comment]
Thank you ! 
I am going to try to find something to fix the problem .
