### ISSUE TITLE
[Fix ] Missing icons

### ISSUE THREAD

**Issue by ghost** [ilnanny/Lila-HD-icon-theme#5]
Hi Erik here from ArchMerge
Installed your icons and see some missing icons.
Can I just list them here and you see when and if you can make them...
After installing archmerge you will see all of them - obs is extra

cool retro term
grsync
feh
nitrogen
obs
openbox menu editor
peek
temps
variety
vivaldi

**Comment by ilnanny** [comment]
Hi Erik 
added icons :+1: 

 Lila_HD/apps/scalable/Temps.svg
 Lila_HD/apps/scalable/cool-retro-term.svg
 Lila_HD/apps/scalable/cs-windows.svg
 Lila_HD/apps/scalable/emoji-picker.svg
 Lila_HD/apps/scalable/feh.svg
 Lila_HD/apps/scalable/grsync.svg
 Lila_HD/apps/scalable/im-icq.svg
 Lila_HD/apps/scalable/ipython2.svg
 Lila_HD/apps/scalable/nitrogen.svg
 Lila_HD/apps/scalable/obmenu.svg
 Lila_HD/apps/scalable/obmenu3.svg
 Lila_HD/apps/scalable/obs.svg
 Lila_HD/apps/scalable/openbox3.svg
 Lila_HD/apps/scalable/openshot.svg
 Lila_HD/apps/scalable/openvpn.svg
 Lila_HD/apps/scalable/peek.svg
 Lila_HD/apps/scalable/qopenvpn.svg
 Lila_HD/apps/scalable/sqlitebrowser.svg
 Lila_HD/apps/scalable/variety.svg
 Lila_HD/apps/scalable/vivaldi-browser.svg
 Lila_HD/apps/scalable/vivaldi-stable.svg
 Lila_HD/apps/scalable/vivaldi.svg
 Lila_HD/apps/scalable/vollyball.svg
on last update.
